name: Compile Anonymized Resume
run-name: ${{ github.actor }} is compiling all resumes with anonymized data
on: [push]
jobs:
  compile-anon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
    - name: Create default personal data file
      run: |
        cp personalinfo_default.sty personalinfo.sty
    - name: Compile resumes
      uses: xu-cheng/latex-action@v2
      with:
        root_file: "resume*.tex"
        glob_root_file: true
    - name: Stage changes
      run: |
        git add -f resume*.pdf
    - name: Commit files
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -a -m "Compile anonymized resume for commit ${GITHUB_SHA}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}